### ISSUE TITLE
GUI Glitch

### ISSUE THREAD

**Issue by msfjarvis** [AndroGeek974/AndroidAutoCompiler2#3]
The GUI, as you said, is giving trouble with frames. What if we dump frames altogether and create input boxes dynamically using the canvas.create function type ? Ask the name of the folder, do that part, then ask ROM name, do repo init, ask if you want to download, then do repo sync and then do the build.

What Say ???

**Comment by DamienBoyer974** [comment]
I thought about it but menu management is cleaner, simply to use... But to release the first full GUI version it can be a solution.

**Comment by msfjarvis** [comment]
Probably.

**Comment by msfjarvis** [comment]
Hey @AndroGeek974, check out pull request #4. And don't hide that smile ;)

**Comment by DamienBoyer974** [comment]
Can be a base yes... Did you see my start.sh update to manage frames ?

**Comment by msfjarvis** [comment]
I did, though personally it's a bit of a mess. I really think mine is the best way out.
