### ISSUE TITLE
Project definition

### ISSUE THREAD

**Issue by faddat** [AndroGeek974/AndroidAutoCompiler2#5]
I'm going to write up a quick project definition in this issue here.  If you like it, can you add it to the readme file?  That way, it'll be a lot clearer what we're trying to accomplish.  
## AndroidAutoCompiler
- What is it?  
  AAC is a system for building android and android-compatible ROMS that requires no knowledge of the linux shell.  
- What devices can I use it for?
  AAC should work with anything that is supported by Cyanogenmod.  
- Which OSes do you want to support?
  - Android (and its variants)
  - Tizen
  - Ubuntu Touch
  - Plasma Mobile
- Why are you making AAC?
  - Because it's much too hard for individuals who want to make their own smartphone operating system software for their own reasons to do so, despite the wide availability of the source code needed.  This is an attempt at an ecosystem patch that should address the difficulty level faced by users.  
  - To ease the development of open source smartphone hardware.
  - In general, to increase people's ability to hack the hardware they've bought.  
- What features do you have planned for the future?
  - Full python3 GUI
  - Support for building from Windows and OSX via Vagrant VirtualBox Virtual Machines.
  - Automatic updates of the build scripts for device variants
  - A library of build scripts for devices, including those not yet supported by Cyangogenmod
  - collaboration with the groups releasing software directly, to ensure that we build their code in the manner recommended by the group itself.  
  -

**Comment by DamienBoyer974** [comment]
@faddat That's perfect!

**Comment by msfjarvis** [comment]
Dude, you should be a lawyer, you write perfect legalese ;)

Do a pull request to the repo. @AndroGeek974's gonna merge it ASAP
